//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Donation
{
    public int DonationKey { get; set; }
    public Nullable<System.DateTime> DonationDate { get; set; }
    public Nullable<decimal> DonationAmount { get; set; }
    public Nullable<int> PersonKey { get; set; }
    public Nullable<int> EmployeeKey { get; set; }

    public virtual Person Person { get; set; }
}

public partial class DonorLogin
{
    public int loginId { get; set; }
    public Nullable<int> PersonKey { get; set; }
    public string LastName { get; set; }
    public string DonorPassword { get; set; }

    public virtual Person Person { get; set; }
}

public partial class Person
{
    public Person()
    {
        this.Donations = new HashSet<Donation>();
        this.DonorLogins = new HashSet<DonorLogin>();
        this.PersonAddresses = new HashSet<PersonAddress>();
        this.PersonContacts = new HashSet<PersonContact>();
    }

    public int PersonKey { get; set; }
    public string LastName { get; set; }
    public string FirstName { get; set; }

    public virtual ICollection<Donation> Donations { get; set; }
    public virtual ICollection<DonorLogin> DonorLogins { get; set; }
    public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
    public virtual ICollection<PersonContact> PersonContacts { get; set; }
}

public partial class PersonAddress
{
    public int PersonAddressKey { get; set; }
    public string Street { get; set; }
    public string Apartment { get; set; }
    public string State { get; set; }
    public string City { get; set; }
    public string Zip { get; set; }
    public Nullable<int> PersonKey { get; set; }

    public virtual Person Person { get; set; }
}

public partial class PersonContact
{
    public int ContactKey { get; set; }
    public string ContactInfo { get; set; }
    public Nullable<int> PersonKey { get; set; }
    public Nullable<int> ContactTypeKey { get; set; }

    public virtual Person Person { get; set; }
}

public partial class Service
{
    public int ServiceKey { get; set; }
    public string ServiceName { get; set; }
    public string ServiceDescription { get; set; }

   
}